### ISSUE TITLE
Demo needed

### ISSUE THREAD

**Issue by nzhl** [NaturalSelectionLabs/RSS3#12]
Still quite confused about the final implement of RSS3,  a runable demo should be helpful~

**Comment by nzhl** [comment]
> Still quite confused about the final implement of RSS3, a runable demo should be helpful~

If this is not possible for current stage, some user stories in real life can also help

**Comment by kallydev** [comment]
This is a simple example for publishing content on an RSS3 endpoint network.

```python
import hexbytes
import requests

from eth_keys import keys

if __name__ == "__main__":
    endpoint = "https://rss3-hub-playground-6raed.ondigitalocean.app"
    pk = "0x47e18d6c386898b424025cd9db446f779ef24ad33a26c499c87bb3d9372540ba"
    pk = keys.PrivateKey(hexbytes.HexBytes(pk))
    address = pk.public_key.to_checksum_address()
    print(address)
    r = requests.get(f"{endpoint}/{address}")
    print(r.json())
```

**Comment by nzhl** [comment]
> This is a simple example of fetching content from the RSS3 endpoint network.
> 
> ```python
> import hexbytes
> import requests
> 
> from eth_keys import keys
> 
> if __name__ == "__main__":
>     endpoint = "https://rss3-hub-playground-6raed.ondigitalocean.app"
>     pk = "0x47e18d6c386898b424025cd9db446f779ef24ad33a26c499c87bb3d9372540ba"
>     pk = keys.PrivateKey(hexbytes.HexBytes(pk))
>     address = pk.public_key.to_checksum_address()
>     print(address)
>     r = requests.get(f"{endpoint}/{address}")
>     print(r.json())
> ```

pretty cool,  seems ppl using public_key as their id to publish content, and private one to denote the ownership ? Any node api provided?

**Comment by DIYgod** [comment]
Yeah, you can try it through [RSS3-Hub](https://github.com/NaturalSelectionLabs/RSS3-Hub) [RSS3-SDK-for-JavaScript](https://github.com/NaturalSelectionLabs/RSS3-SDK-for-JavaScript) [RSS3-Python-SDK](https://github.com/lazzyRabbit/RSS3-Python-SDK) and some upcoming [libraries](https://github.com/NaturalSelectionLabs/awesome-rss3)
