### ISSUE TITLE
Scroll bar missed

### ISSUE THREAD

**Issue by vgjm** [NaturalSelectionLabs/RSS3#20]
There is no scroll bar on the [Edit Profile Page](https://yohoo.eth.rss3.bio/profile) when I set scalability to 100%.

**Comment by vgjm** [comment]
Sorry, There is a scroll bar, but I can't scroll down to see the discard and save buttons.

**Comment by Candinya** [comment]
Since it's a Web3Pass related issue and has nothing to do with RSS3 protocol itself, you may like to re-open this in [Web3Pass](https://github.com/NaturalSelectionLabs/Web3Pass/issues/new?assignees=&labels=&template=bug_report.md&title=) repo.
