### ISSUE TITLE
About name service: how to find a persona

### ISSUE THREAD

**Issue by DIYgod** [NaturalSelectionLabs/RSS3#5]
The proposal has unique ids in persona files for finding files and authentication, but finding and subscribing to personas through complex and meaningless ids is a bad idea, so a name service is needed

There are two ways that come to mind

1. name as filename, i.e. names take over the function of finding files, the advantage of this is that it is more efficient, the disadvantage is that the name service would be tied to the corresponding distributed network, which would make the different networks more fragmented and require two pieces of information to find a persona: network + name

2. id as a filename and making a DNS-like system, which has the opposite advantages and disadvantages of 1

**Comment by joshuaTTL** [comment]
We'll need more investigation regarding naming service later. But it's definitely important.

**Comment by DIYgod** [comment]
With the popularity of domain name services such as ENS, this is no longer an issue
cc https://github.com/NaturalSelectionLabs/Web3-Name-Service
